### ISSUE TITLE
Review remarks from Stefan Oehme

### ISSUE THREAD

**Issue by sadovnikov** [JV-ration/project-info-plugins#1]
@oehme, thanks for code review! I'm very new with Gradle, so it will take some time to process them

- [x] The impl class should live in the plugin and does not need to implement the interface. The mapping is purely reflection based
- [x] the usage should be greatly simplified. The user should not have to deal with the init script. Your retriever should bundle it. In concrete terms: bundle it in your jar, extract it to a tmp dir and apply it automatically.
- [x] There's no reason for two plugins. The task and model should be provided by the same plugin.

**Comment by sadovnikov** [comment]
- [ ] The impl class should live in the plugin and does not need to implement the interface. The mapping is purely reflection based

Yes, perfect. There is no reason to expose implementation class in `gradle-model` project. May implementation class implement the interface, so compiler insures consistency?

- [ ] the usage should be greatly simplified. The user should not have to deal with the init script. Your retriever should bundle it. In concrete terms: bundle it in your jar, extract it to a tmp dir and apply it automatically.

Yes, this is my idea too. It will be implement. However users will have to deal with init script if they want to use `project-info` task

- [ ] There's no reason for two plugins. The task and model should be provided by the same plugin

I tried to do this, but failed. Model plugin implements `Plugin<Project>`, the task plugin implements `Plugin<Gradle>`. Implementation of `Plugin<Gradle>` allows attaching the new task to the root project only. Am I missing something?

**Comment by oehme** [comment]
> However users will have to deal with init script if they want to use project-info task

No, your plugin should be published to the [plugin portal](https://plugins.gradle.org/) so users can just apply it.

> the task plugin implements Plugin<Gradle>

There's no reason for it to implement `Plugin<Gradle>`, it should be a `Plugin<Project>`

**Comment by oehme** [comment]
Great improvements!

> May implementation class implement the interface, so compiler insures consistency

Yes, it may.
